tasks:
  - init: npm install
    command: npm start
  - command: echo "Try running `npm run create:blog`"
ports:
  - port: 8000
    onOpen: open-browser
github:
  prebuilds:
    master: true
    branches: true
