[build]
  publish = "public"
# TODO use gatsby plugin algolia instead, so we can index content types better
[[plugins]]
  package = "@algolia/netlify-plugin-crawler"
    [plugins.inputs]
    branches = ['3022']
# These redirects will be used by Netlify as well as the client to replace link addresses
# 2019 Redirects
[[redirects]]
  from = "/wiki"
  to = "https://github.com/ethereumclassic/wiki/wiki"
[[redirects]]
  from = "/teams"
  to = "/ecosystem/teams"
[[redirects]]
  from = "/roadmap"
  to = "/knowledge/roadmap"
[[redirects]]
  from = "/summit/2019"
  to = "/press/conferences"
[[redirects]]
  from = "/blog/2016-07-11-manifesto"
  to = "/blog/2016-07-11-crypto-decentralist-manifesto"
[[redirects]]
  from = "/blog/2016-07-15-start-project"
  to = "/blog/2016-07-15-start-ethereum-classic-project"
[[redirects]]
  from = "/blog/2016-10-17-hard-fork"
  to = "/blog/2016-10-17-gas-reprice-hard-fork"
[[redirects]]
  from = "/blog/2017-01-17-newsletter"
  to = "/blog/2017-01-17-die-hard-fork-upgrade"
# 2021 Redirects
[[redirects]]
  from = "/ecosystem/exchanges"
  to = "/services/exchanges"